name: 'Integration test API'
on:
    schedule:
        - cron: '0 5 * * */2'
    workflow_dispatch:

jobs:
    runIntegrationTest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2-beta
              with:
                  node-version: '12'
            - name: 'Run Integration test'
              env:
                  SOFAR_API_TOKEN: ${{ secrets.SOFAR_API_TOKEN }}
              run: |
                  npm install
                  yarn integration-test
