name: Publish tagged versions to NPM

on:
    push:
        branches: test/*
        tags: releases/*

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2-beta
              with:
                  node-version: '12'
            - name: Get the version
              id: get_version
              run: |
                  echo ::set-output name=TAG_VERSION::${GITHUB_REF#refs/tags/releases/}
                  echo ::set-output name=TAG_VERSION::${GITHUB_REF#refs/heads/test/}
                  echo ::set-output name=PACKAGE_VERSION::$(node -p -e "require('./package.json').version")

            - name: Validate tag version to package version
              shell: bash
              env:
                  TAG_VERSION: ${{ steps.get_version.outputs.TAG_VERSION }}
                  PACKAGE_VERSION: ${{ steps.get_version.outputs.PACKAGE_VERSION }}
              run: |
                  if [ "${TAG_VERSION}" != "${PACKAGE_VERSION}" ]; then
                    echo "::error ::Tag version number '${TAG_VERSION}' does not equal package.json version number '${PACKAGE_VERSION}'!"
                    exit 1;
                  fi

            - name: npm install test and publish
              shell: bash
              # The NPMJS auth token is a github project secret containing an auth token genereated by and under the account of Dominik Fretz
              env:
                  NPMJS_AUTH_TOKEN: ${{ secrets.NPMJS_AUTH_TOKEN }}
              run: |
                  npm install
                  npm test
                  echo "//registry.npmjs.org/:_authToken=${NPMJS_AUTH_TOKEN}" > .npmrc
                  npm publish --scope public --dry-run
