name: Publish tagged versions to NPM

on:
    push:
        branches: test/*
        tags: releases/*

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2-beta
              with:
                  node-version: '12'
            - name: Get the version
              id: get_version
              run: |
                  echo ::set-output name=TAG_VERSION::${GITHUB_REF#refs/tags/releases/}
                  echo ::set-output name=PACKAGE_VERSION::$(node -p -e "require('./package.json').version")

            - shell: bash
              env:
                  TAG_VERSION: ${{ steps.get_version.outputs.TAG_VERSION }}
                  PACKAGE_VERSION: ${{ steps.get_version.outputs.PACKAGE_VERSION }}
              run: |
                  echo "TAG_VERSION: ${TAG_VERSION} - PACKAGE_VERSION: ${PACKAGE_VERSION}

            - run: npm install
            - run: npm test
            - shell: bash
              # The NPMJS auth token is a github project secret containing an auth token genereated by and under the account of Dominik Fretz
              env:
                  NPMJS_AUTH_TOKEN: ${{ secrets.NPMJS_AUTH_TOKEN }}
              run: |
                  echo "//registry.npmjs.org/:_authToken=${NPMJS_AUTH_TOKEN}" > .npmrc
                  npm publish --scope public --dry-run
